exclude: ["Gemfile", "Gemfile.lock", "Rakefile", "README.md", "sass", vendor]
markdown: kramdown

sass:
  style: :compressed
  # Where you keep your scss files
  sass_dir: assets/css/
  # Where sass should look for other scss
  load_paths:
    - _sass/
